Fix error on travis while building pycairo
Fails due to too old cairo version on xenial:

Requested 'cairo >= 1.15.10' but version of cairo is 1.14.6

ERROR: Could not build wheels for pycairo which use PEP 517 and cannot
be installed directly